info:
  welcome: Привет! Это генератор искусства на основе технологии Stable Diffusion
  select_model: Выбери свою <b>модель</b>
  select_orientation_mode: Выбери ориентацию изображения
  canceled: ✅ Отменено
  in_progress: Генерирую изображения
  in_progress_text: Генерирую изображения
  in_progress_img: Генерирую изображения
  in_progress_rescale: Увеличиваю качество изображения

  scores:
    creativity: Креативность
    skill: Навык

help:
  txt2img: Отправь текст для создания изображения по его описанию
  img2img: Чтобы изменить изображение, отправь его с описанием
  rescale: Отправь изображение отдельно, чтобы увеличить его разрешение
  model: /model - Выбери модель SD
  orientaiton: /picrute_orientation - Изменение ориентации изображения
  retry: /retry - Перезапустить генерацию с предыдущими параментами

warning:
  wait_or_cancel: Пожалуйста подожди
  message_editing: Редактирование сообщений не поддерживается
  nothing_to_cancel: <i>Нечего отменять</i>
  long_queue: Очередь слишком длинная, придется подождать

error:
  bad_action: Эта фича еще не внедрена
  whitelist: Ошибка. Тебя нет в белом списке
  bad_message: Этот тип сообщения не поддерживается
  generation_error: Ошибка при генерации изображения
  unhandled_error: Неизвесная ошибка

bot_commands:
  model: Изменение используемой модели
  orientation: Изменение ориентации сгенерированного изображения
  retry: Перезапустить генерацию
  help: Помощь

orientation:
  square: Квадрат
  portrait: Портрет
  landscape: Ландшафт

model0:
  name: Stable Diffusion 1.5
  description: Самая популярная генеративная нейронная сеть на основе Stable Diffusion. Неплохо работает для любого типа изображений

model1:
  name: sample_name 👀
  description: etc. Works with <i>HTML</i>
